FROM node:14.17.1-alpine
RUN mkdir /DEMO-DOCKERIZE-NODEJS
COPY index.js /DEMO-DOCKERIZE-NODEJS
COPY package.json /DEMO-DOCKERIZE-NODEJS
COPY student.json /DEMO-DOCKERIZE-NODEJS
WORKDIR /DEMO-DOCKERIZE-NODEJS
RUN npm install
EXPOSE 3000
CMD node index.js
